{{- if .Values.networkPolicy.enabled }}
{{- range .Values.networkPolicy.ingress.allowedNamespaces }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $.Values.app.name }}-allow-from-{{ .name }}
  namespace: {{ $.Values.namespace.name }}
  labels:
    app: {{ $.Values.app.name }}
    policy-type: ingress
spec:
  podSelector:
    matchLabels:
      app: {{ $.Values.app.name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              {{- range $key, $value := .namespaceLabels }}
              {{ $key }}: {{ $value | quote }}
              {{- end }}
      ports:
        {{- range .ports }}
        - port: {{ .port }}
          protocol: {{ .protocol }}
        {{- end }}
{{- end }}
{{- end }}
